export interface ClusterCatalogue {
  domain: string;
  cluster: string;
  minimumDifficulty: number;
  maximumDifficulty: number;
  zeroCount?: number;
  names: string[];
}

function catalogue(
  domain: string,
  cluster: string,
  minimumDifficulty: number,
  maximumDifficulty: number,
  names: string,
  zeroCount = 0,
): ClusterCatalogue {
  return {
    domain,
    cluster,
    minimumDifficulty,
    maximumDifficulty,
    zeroCount,
    names: names.split("|").map((name) => name.trim()).filter(Boolean),
  };
}

export const PASS2_CATALOGUE: ClusterCatalogue[] = [
  catalogue("body", "floor", 0, 2,
    "Track a moving object|Turn toward a nearby sound|Hold the head upright|Bring both hands together|Open and close one hand|Transfer an object between hands|Point to a nearby target|Shift weight while seated|Sit upright for one minute|Roll from back to side|Move from lying to sitting|Reach across the body|Place an object at a target|Stand with hand support|Lower from standing to sitting|Step sideways with support|Bend and straighten the knees|Turn around while standing|Pick up an object from the floor|Step over a low obstacle", 20),
  catalogue("body", "locomotion", 0, 5,
    "Take ten supported steps|Walk ten metres unaided|Stop safely while walking|Change direction while walking|Walk up a gentle slope|Walk down a gentle slope|Climb one flight of stairs|Descend one flight of stairs|Walk while carrying a light object|Match another person's walking pace|Walk through a crowded space|Cross a shallow step safely|Walk for twenty minutes|Hike a marked trail|Navigate loose ground on foot|Climb a steep path|Descend a steep path safely|Move efficiently over mixed terrain|Pace a two-hour walk", 4),
  catalogue("body", "balance-coordination", 0, 6,
    "Catch a slowly tossed ball|Throw a ball to a target|Kick a stationary ball|Step to a repeated beat|Alternate hands in a simple pattern|Turn and stop on command|Walk heel to toe for five metres|Catch a ball while moving|Throw to a moving partner|Coordinate hands and feet in sequence|Change rhythm without losing the pattern|Perform a mirrored movement sequence|Adapt a sequence to a partner", 8),
  catalogue("body", "strength-carry", 1, 6,
    "Lift a light object from the floor|Carry a balanced load in both hands|Push a loaded door open|Pull an object across a smooth floor|Rise from a chair five times|Hold a light object overhead|Carry five kilograms for twenty metres|Lift a ten-kilogram object safely|Push a loaded cart for fifty metres|Carry an uneven load safely|Move a bulky object with a partner|Lift repeated loads with stable form|Carry fifteen kilograms over stairs"),
  catalogue("body", "endurance", 1, 7,
    "Walk continuously for ten minutes|Climb stairs for five minutes|Cycle continuously for fifteen minutes|Sustain moderate movement for twenty minutes|Walk briskly for thirty minutes|Jog continuously for ten minutes|Cycle continuously for one hour|Swim continuously for fifteen minutes|Hike for three hours with breaks|Pace a one-hour continuous effort|Complete repeated effort intervals|Sustain a two-hour endurance effort|Plan and pace an all-day endurance effort"),
  catalogue("body", "water-and-wheels", 1, 6,
    "Float with support for thirty seconds|Enter shallow water safely|Exit shallow water safely|Glide through water for five metres|Tread water for one minute|Swim ten metres to an exit|Mount and dismount a bicycle|Brake a bicycle smoothly|Steer a bicycle around obstacles|Signal while cycling|Control a bicycle on varied surfaces"),
  catalogue("body", "fine-motor", 0, 5,
    "Pinch and release a small object|Stack five small objects|Thread a large opening|Turn a page one at a time|Trace a straight line|Fold paper along a line|Fasten a large button|Tie a simple knot|Place ten pegs accurately|Cut along a marked line|Manipulate two small parts together", 11),

  catalogue("lang", "writing", 1, 7,
    "Write a complete sentence|Write a clear question|Write a short instruction|Write a five-sentence account|Organise a paragraph around one point|Use punctuation to separate ideas|Write a concise request|Write a factual event summary|Write a comparison of two options|Write a persuasive paragraph|Draft a two-page explanation|Revise writing for clarity|Adapt tone for a named audience|Structure a multi-section document|Integrate evidence into an argument|Write a coherent long-form essay|Edit for consistency across sections|Write a technical explanation for non-specialists|Develop a sustained written argument|Rewrite complex material in plain language|Produce a publication-ready article|Develop a coherent book-length argument"),
  catalogue("lang", "reading", 0, 6,
    "Match a written label to an object|Locate a named word on a page|Follow a two-step written direction|Identify the main sentence in a paragraph|Read a short notice accurately|Use headings to locate information|Follow a short written procedure|Identify who did what in a narrative|Infer a word's meaning from context|Locate evidence for a stated claim|Follow cross-references in a document|Compare information in text and a table|Read a twenty-page text for detail|Detect a contradiction within a document|Interpret a writer's qualified claim|Read an unfamiliar technical instruction|Analyse structure across several chapters|Read a long argument critically|Compare rhetorical choices in two texts|Interpret a dense specialised text", 6),
  catalogue("lang", "speaking-listening", 1, 6,
    "State a need in one sentence|Repeat a spoken instruction accurately|Give a two-step spoken direction|Describe a familiar object clearly|Retell a short spoken account|Ask for clarification during conversation|Explain a process in sequence|Follow a five-minute spoken explanation|Adjust speaking pace for a listener|Paraphrase another person's statement|Deliver a clear two-minute explanation|Interpret implied meaning in conversation|Sustain a structured interview|Explain a complex issue without notes|Moderate a detailed spoken exchange|Adapt live speech for mixed audiences"),
  catalogue("lang", "comprehension-summary", 2, 6,
    "Identify a text's central point|Distinguish examples from conclusions|Summarise a short spoken account|Extract an argument's supporting reasons|Compare two accounts of one event|Condense a page into five points|Trace references across a document|Summarise a thirty-minute discussion|Reconcile details across three sources|Separate stated facts from implications|Produce an executive summary|Synthesize a long technical document"),
  catalogue("lang", "second-language", 1, 7,
    "Exchange greetings in another language|Ask for a location in another language|Give personal details in another language|Follow a simple transaction in another language|Describe a routine in another language|Handle an unexpected travel question bilingually|Read a short practical notice in another language|Write a concise message in another language|Sustain a twenty-minute bilingual conversation|Interpret a practical conversation between languages"),

  catalogue("social", "conversation", 0, 5,
    "Take turns in a short exchange|Signal that a speaker should continue|Answer a direct social question|Introduce one person to another|Close a conversation politely|Join an ongoing group conversation|Shift topics with a clear transition|Clarify a mistaken assumption|Maintain a conversation for fifteen minutes|Adapt detail to another person's interest|Include a newcomer in a discussion|Discuss a sensitive topic respectfully|Navigate competing conversational goals|Sustain rapport across repeated meetings|Host a structured networking conversation|Facilitate a difficult one-to-one conversation", 5),
  catalogue("social", "conflict-negotiation", 2, 6,
    "State a disagreement without accusation|Separate positions from interests|Ask for a concrete change|Propose two workable compromises|Set a boundary during disagreement|De-escalate a heated exchange|Negotiate a shared-resource schedule|Document an agreed resolution|Handle an impasse without escalation|Negotiate across unequal priorities|Resolve a recurring two-party dispute|Design a fair multi-issue agreement|Facilitate agreement under time pressure|Rebuild cooperation after conflict"),
  catalogue("social", "feedback-teaching", 2, 6,
    "Demonstrate one procedure step by step|Check whether an instruction was understood|Correct one error without discouraging practice|Set a measurable practice target|Explain the reason for a correction|Adapt an explanation after confusion|Give balanced performance feedback|Teach a short procedure to a novice|Observe practice using clear criteria|Plan a thirty-minute teaching session|Sequence instruction from simple to complex|Diagnose a learner's recurring error|Design practice for mixed ability levels|Evaluate whether teaching changed performance"),
  catalogue("social", "listening-empathy", 1, 6,
    "Name the feeling expressed by a speaker|Summarise a speaker's concern|Ask before offering advice|Distinguish feelings from requested actions|Listen for five minutes without interrupting|Validate an experience without claiming agreement|Clarify an ambiguous emotional statement|Support someone through a difficult disclosure|Recognise when practical help is wanted|Maintain boundaries during emotional support|Respond to distress without taking control|Sustain supportive listening over repeated conversations|Coordinate peer support while preserving privacy"),
  catalogue("social", "groups-facilitation", 2, 7,
    "Open a small group discussion|Invite input from a quiet participant|Keep a discussion on one question|Record group decisions visibly|Summarise areas of agreement|Redirect a dominating participant|Run a ten-minute round-robin|Facilitate a structured decision|Manage competing topics in a meeting|Guide a group through prioritisation|Facilitate a contentious workshop|Facilitate multi-party crisis dialogue|Design an inclusive participation process|Coordinate multiple facilitators"),
  catalogue("social", "presenting", 1, 6,
    "Introduce a topic in thirty seconds|Explain one visual aid clearly|Speak audibly to a small group|Present three points in sequence|Answer one audience question directly|Deliver a ten-minute prepared talk|Present without reading a script|Adjust a talk after audience feedback|Explain numerical findings aloud|Handle a challenging question calmly|Deliver a persuasive twenty-minute presentation"),

  catalogue("care", "first-aid", 1, 6,
    "Apply a clean dressing|Check responsiveness and breathing|Treat a minor burn with cool water|Support a minor sprain|Place an unresponsive breathing person safely|Recognise signs requiring urgent help|Manage a nosebleed safely|Respond to choking in a conscious adult|Perform chest compressions on a training aid|Use an automated defibrillator trainer|Monitor a casualty until help arrives|Respond to suspected shock|Immobilise a suspected limb injury|Prioritise care for two casualties"),
  catalogue("care", "hygiene-selfcare", 1, 5,
    "Brush teeth for two minutes|Clean and cover a small graze|Trim fingernails safely|Wash the body independently|Maintain reusable hygiene items|Choose clothing for weather conditions|Complete a morning self-care sequence|Adapt self-care around a temporary limitation|Track and replenish personal care supplies|Plan self-care for a multiday journey"),
  catalogue("care", "emergency-response", 1, 6,
    "State an emergency location clearly|Move away from an immediate danger|Alert nearby people to danger|Follow an evacuation instruction|Choose a safe assembly point|Give responders a concise situation report|Guide another person to an exit|Use a fire blanket on a training setup|Coordinate a small-area evacuation|Account for people after evacuation"),
  catalogue("care", "injury-prevention", 1, 6,
    "Clear a walking path of trip hazards|Adjust a work surface to neutral posture|Lift a light object with stable posture|Warm up before vigorous movement|Choose footwear for the activity surface|Set up lighting for a manual task|Plan rest breaks for repetitive work|Spot another person's lift safely|Modify an activity after pain appears|Design an injury-prevention checklist|Audit a repeated task for strain risks"),
  catalogue("care", "risk-assessment", 1, 6,
    "Distinguish a hazard from its consequence|Estimate likelihood using three categories|Estimate severity using three categories|Choose one control for a simple hazard|Reassess risk after a condition changes|Compare two risk-control options|Document a five-hazard assessment|Prioritise controls by effectiveness"),
  catalogue("care", "sleep-rest", 1, 5,
    "Prepare a low-stimulation rest space|Plan a consistent sleep opportunity|Take a twenty-minute restorative break|Adjust a rest plan after poor sleep|Protect a rest period from interruptions|Plan recovery between demanding days|Track sleep conditions for one week"),

  catalogue("food", "heat-technique", 1, 6,
    "Bring water to a controlled simmer|Boil food without overflowing|Steam food until evenly cooked|Sauté food without scorching|Turn food for even browning|Judge doneness by temperature|Roast food evenly|Simmer a sauce to target thickness|Control two pans at once|Recover a sauce that begins to split|Cook with retained heat|Coordinate oven and stovetop timing|Adapt heat to unfamiliar cookware|Execute a three-stage cooking method|Manage heat across a large batch|Develop repeatable cooking times"),
  catalogue("food", "knife-prep", 1, 5,
    "Hold a kitchen knife safely|Stabilise food before cutting|Slice soft food evenly|Dice firm food into equal pieces|Mince an ingredient consistently|Peel produce with minimal waste|Separate edible parts from trim|Cut thin strips uniformly|Portion a large ingredient safely|Sharpen a kitchen knife with a guide|Maintain a consistent cutting rhythm|Prepare mixed ingredients to matched sizes|Break down a whole vegetable efficiently"),
  catalogue("food", "baking", 2, 6,
    "Measure baking ingredients accurately|Mix a batter without overworking it|Knead dough to a smooth texture|Judge dough fermentation by volume|Shape equal portions of dough|Bake a simple loaf consistently|Adjust baking time for portion size|Create a stable whipped mixture|Prepare a laminated dough|Diagnose texture faults in baked food|Scale a baking formula to a new yield"),
  catalogue("food", "kitchen-safety", 1, 5,
    "Store chilled food promptly|Check food temperature safely|Separate raw and ready-to-eat preparation|Cool cooked food safely|Reheat food evenly|Extinguish a small pan fire safely|Sanitise a food-contact surface|Discard unsafe food using clear criteria|Plan safe flow through a shared kitchen"),
  catalogue("food", "seasoning-tasting", 1, 5,
    "Identify salt intensity in a sample|Compare acidity in two foods|Recognise excessive bitterness|Adjust seasoning in small increments|Balance salt and acidity|Use aroma to compare freshness|Match seasoning intensity to a main ingredient|Correct an oversalted mixture|Build flavour in stages"),
  catalogue("food", "meal-planning", 2, 6,
    "Plan one balanced meal from available food|Create a shopping list from a menu|Use perishable food before it spoils|Plan meals around two dietary constraints|Batch overlapping preparation tasks|Estimate portions for four people|Plan five meals within a fixed budget|Adapt a menu after an ingredient shortage"),
  catalogue("food", "hosting", 2, 6,
    "Set a table for a shared meal|Time one hot and one cold dish|Serve food at safe temperatures|Coordinate seating and serving for six|Adapt service for stated dietary needs"),

  catalogue("home", "hand-tools", 1, 6,
    "Select the right screwdriver tip|Measure a length twice consistently|Mark a straight cutting line|Tighten a fastener without stripping it|Use pliers to grip a small part|Drive a nail without bending it|Saw along a marked line by hand|Drill a straight pilot hole|Clamp a workpiece securely|Level a mounted object|Cut a joint to a measured fit|Maintain and store hand tools safely"),
  catalogue("home", "repair-assembly", 1, 6,
    "Identify matching assembly parts|Follow a six-step assembly diagram|Replace a worn handle|Tighten a loose joint|Align two parts before fastening|Repair a small surface crack|Replace a simple mechanical fitting|Diagnose a sticking hinge|Reinforce a weak furniture joint|Disassemble and reassemble a mechanism|Plan a repair from observed symptoms"),
  catalogue("home", "cleaning-laundry", 1, 5,
    "Separate washable items by care needs|Measure a cleaning product safely|Remove a fresh water-based stain|Clean a hard surface without damage|Dry clothing to prevent distortion|Hand-wash a delicate item|Clean a room in an efficient sequence|Treat an old stain using a test patch|Choose a cleaning method for an unfamiliar surface|Plan a whole-space deep clean|Restore a heavily soiled washable item"),
  catalogue("home", "electrical-plumbing-basics", 2, 6,
    "Locate a utility shutoff|Reset a tripped protective switch|Clear a simple drain blockage|Replace a tap washer|Test whether a circuit is de-energised|Replace a low-voltage fitting|Diagnose a continuously running toilet|Seal a small threaded plumbing joint|Trace the source of a minor leak"),
  catalogue("home", "textiles-sewing", 1, 5,
    "Thread a hand-sewing needle|Sew a straight hand seam|Repair a small fabric tear|Hem a straight edge by hand|Replace a simple fastener|Take body measurements for a garment|Adjust a pattern for length|Construct a simple fabric item"),
  catalogue("home", "gardening", 1, 5,
    "Sow seeds at a stated depth|Water a container without runoff|Repot a plant without damaging roots|Prune a dead stem cleanly|Diagnose under-watering from plant signs"),
  catalogue("home", "vehicle-basics", 2, 6,
    "Check tyre pressure against a label|Top up windscreen fluid safely|Check exterior lights|Identify a dashboard warning that requires stopping|Jump-start a vehicle with protected connections"),

  catalogue("reason", "logic-argument", 1, 6,
    "Identify a conclusion in a short argument|List the premises supporting a claim|Distinguish a reason from an example|Test whether a conclusion follows|Find an unstated assumption|Construct a valid two-step argument|Identify a contradiction between claims|Distinguish necessary from sufficient conditions|Evaluate a counterexample|Compare two explanations against evidence|Revise an argument after a valid objection|Analyse a circular argument|Formalise a complex conditional argument|Evaluate a long chain of reasoning"),
  catalogue("reason", "arithmetic", 1, 5,
    "Add three two-digit numbers|Subtract with regrouping|Multiply two two-digit numbers|Divide a quantity into equal shares|Estimate a calculation before solving|Calculate an average of five values|Convert between metric units|Calculate a proportional share|Apply compound percentage changes|Reconcile a list of transactions|Check a multistep calculation by another method|Calculate a weighted average"),
  catalogue("reason", "algebra-symbolic", 2, 6,
    "Substitute values into a formula|Simplify a symbolic expression|Rearrange a formula for one variable|Solve two simultaneous linear equations|Plot a linear relationship from a formula|Interpret the slope of a relationship|Solve a quadratic equation|Represent a word problem symbolically|Manipulate inequalities without changing meaning|Analyse an exponential relationship|Derive a formula from stated constraints|Solve a system with several variables|Verify a symbolic derivation"),
  catalogue("reason", "probability-statistics", 2, 6,
    "Calculate probability from equally likely outcomes|Estimate probability from observed frequency|Distinguish correlation from causation|Calculate a median and range|Choose a representative summary statistic|Interpret a confidence interval|Compare risk using absolute frequencies|Design a simple random sample|Detect a misleading graph scale|Fit a simple trend to observations|Test a claim using sample data|Analyse uncertainty in a forecast"),
  catalogue("reason", "estimation-modelling", 2, 7,
    "Estimate an order of magnitude|Break an estimate into measurable factors|Set upper and lower bounds|Check a model against one observation|Perform a sensitivity check|Build a simple rate model|Calibrate a model from observed data|Compare competing models|Quantify uncertainty in an estimate|Model feedback between two quantities|Validate a model on held-out observations|Design a scenario simulation"),
  catalogue("reason", "geometry-measurement", 1, 5,
    "Measure length to the nearest millimetre|Measure an angle with a guide|Calculate the area of a rectangle|Calculate the volume of a rectangular object|Scale a drawing from measurements|Triangulate an inaccessible distance|Check dimensional consistency"),

  catalogue("digital", "documents-spreadsheets", 1, 6,
    "Format a readable one-page document|Create a bulleted list|Insert and label a table|Apply a consistent heading structure|Sort a data table by two fields|Filter rows using two conditions|Write a formula using cell references|Calculate a conditional total|Create a chart with labelled axes|Validate entries against allowed values|Join data from two tables|Summarise data with a pivot table|Protect input cells from accidental edits|Document a workbook's assumptions|Audit formulas for inconsistent references|Build a reusable calculation template"),
  catalogue("digital", "devices-os", 1, 7,
    "Connect a device to a wireless network|Install an operating-system update|Choose an accessible input setting|Connect a peripheral and test it|Manage application permissions|Free storage without deleting needed files|Create a local user account|Back up a device to removable storage|Restore a device from a backup|Diagnose a failing peripheral|Resolve an application conflict|Restore a distributed digital archive|Recover access after a system failure|Migrate data between devices"),
  catalogue("digital", "files-directories", 1, 5,
    "Rename a file descriptively|Move files between folders|Copy a file without changing the original|Find a file by name and date|Create a compressed archive|Extract an archive safely|Apply a consistent file-naming scheme|Compare two file versions|Recover a deleted file from a holding area|Organise a shared folder for retrieval|Design a long-term archive structure"),
  catalogue("digital", "browsing-search", 1, 5,
    "Open a web address directly|Use a specific search phrase|Narrow search results by date|Find text within a long page|Open a link in a separate tab|Compare three search results|Distinguish an advertisement from a result|Trace a claim to its original page|Use exclusion terms in a search|Archive a web source with its date|Conduct a reproducible web search"),
  catalogue("digital", "media-handling", 1, 6,
    "Rotate an image without distortion|Resize an image to stated dimensions|Trim an audio recording|Clip a section from a video|Adjust image brightness without clipping|Remove background noise from speech|Export media in a stated format|Add accurate captions to a short video|Balance speech and music levels|Convert media while preserving quality|Prepare images for several screen sizes"),
  catalogue("digital", "digital-safety", 1, 6,
    "Create a unique account password|Enable an additional sign-in factor|Recognise a suspicious web address|Check an application's requested permissions|Share a file with limited access|Remove hidden location data from a photo|Review account recovery options|Respond to a suspected account compromise|Verify a software download source|Configure encrypted device storage"),

  catalogue("world", "money-budgeting", 1, 6,
    "Record ten transactions accurately|Separate fixed and variable costs|Calculate the total cost of instalments|Set a weekly spending limit|Reconcile a statement against records|Compare offers using total cost|Build a one-month cash-flow plan|Plan for an irregular expense|Adjust a budget after income changes|Evaluate a loan using effective cost|Model three long-term savings scenarios|Audit a complex household budget"),
  catalogue("world", "time-planning", 1, 6,
    "Estimate the duration of a routine task|Place five tasks in dependency order|Reserve travel time between commitments|Break a deadline into dated steps|Choose priorities for one day|Revise a schedule after a delay|Plan a week around fixed constraints|Coordinate availability across four people|Build contingency time into a plan|Balance several projects across a month|Create a rolling three-month plan|Optimise a constrained shared schedule|Coordinate a year-long programme"),
  catalogue("world", "orientation-navigation", 1, 6,
    "Orient a map to the surroundings|Identify the next landmark on a route|Retrace a route from memory|Estimate walking distance from map scale|Choose between two public routes|Navigate an unfamiliar building|Follow a route using cardinal directions|Reroute after missing a turn|Plan an accessible route around barriers|Navigate where location signals are unavailable|Combine several transport modes on one route|Plan an emergency alternative route|Navigate a multi-day journey from maps"),
  catalogue("world", "contracts-admin", 1, 6,
    "Locate a deadline in a form|Gather required documents from a checklist|Keep a dated record of a request|Compare two clauses for differences|Identify an obligation in an agreement|Submit a correction to an application|Track an application through three stages|Summarise a contract's key duties|Prepare evidence for an administrative appeal|Negotiate a clear service amendment|Audit a set of interdependent agreements"),
  catalogue("world", "project-work", 2, 7,
    "Define a project outcome in one sentence|Break an outcome into deliverables|Assign an owner and date to each task|Track blockers in a shared log|Run a fifteen-minute progress review|Update a plan after scope changes|Estimate effort for a small project|Manage dependencies across three contributors|Record and resolve project risks|Direct a multi-year programme|Coordinate work across two teams|Recover a delayed project plan|Design governance for a complex programme"),
  catalogue("world", "travel", 1, 6,
    "Pack from a weather-based checklist|Check entry and transit requirements|Compare routes by time and transfers|Plan arrival from a transport terminal|Keep essential documents accessible|Adapt a journey after cancellation|Plan a week-long independent trip"),
  catalogue("world", "civic-navigation", 2, 6,
    "Find the responsible public service|Locate eligibility rules for a service|Prepare a factual service complaint|Track a public request to resolution"),

  catalogue("learn", "study-technique", 1, 5,
    "Set a question for a study session|Remove two distractions before study|Divide a topic into study blocks|Alternate recall and review|Schedule three focused study sessions|Test progress without looking at notes|Revise a study plan after a weak result|Plan study across four weeks|Adapt study methods to task type"),
  catalogue("learn", "source-evaluation", 2, 6,
    "Identify the author of a source|Locate a source's publication date|Separate primary from secondary evidence|Check whether a source supports a quoted claim|Compare expertise across two sources|Identify an undisclosed conflict of interest|Evaluate the method behind a claim|Cross-check a claim with independent sources"),
  catalogue("learn", "memory", 1, 5,
    "Recall a five-step sequence|Use a location cue to retrieve an item|Group twenty items into categories|Create retrieval questions from notes|Recall key points after one week|Diagnose which material is not retained"),
  catalogue("learn", "notes-capture", 1, 5,
    "Record a source beside each note|Separate quotations from paraphrases|Capture decisions during a meeting|Summarise a page in three notes|Link related notes across two topics|Create an index for a note collection|Convert rough notes into a structured outline"),
  catalogue("learn", "synthesis", 3, 7,
    "Compare conclusions from three sources|Organise evidence by competing explanations|Reconcile conflicting definitions|Build a concept map from five sources|Write a synthesis that preserves disagreement|Transfer an explanatory model to a new topic"),
  catalogue("learn", "deliberate-practice", 2, 6,
    "Choose one measurable practice variable|Design a drill for a recurring error|Record ten practice attempts consistently|Increase task difficulty after stable success"),

  catalogue("art", "music", 1, 7,
    "Match a sung pitch|Clap a four-beat rhythm|Repeat a short melody by ear|Read a simple rhythmic pattern|Play a five-note scale evenly|Tune an instrument to a reference|Accompany a melody with a repeated pattern|Maintain an independent part in a duet|Transpose a simple melody|Improvise over a repeating harmonic pattern|Arrange a piece for three parts|Perform a twenty-minute programme|Compose a complete short piece|Rehearse an ensemble section efficiently|Direct a small ensemble|Orchestrate a multi-section composition|Compose and realise a large ensemble work"),
  catalogue("art", "drawing", 1, 6,
    "Draw five distinct line weights|Block in simple shapes from observation|Shade a sphere from one light source|Measure proportions by sight|Draw overlapping forms clearly|Render three surface textures|Construct a room in one-point perspective|Draw a figure in a timed pose|Compose three objects within a frame|Control value across a complete drawing|Draw reflective material from observation|Develop a consistent visual shorthand|Construct a complex scene in perspective|Create a sustained observational drawing"),
  catalogue("art", "design-visual", 1, 6,
    "Align elements to a shared edge|Create contrast between heading and body text|Group related elements by spacing|Build a three-colour palette|Design a clear visual hierarchy|Lay out information on one page|Create a reusable visual component|Adapt a layout to two screen sizes|Design a symbol set with shared rules|Test a design for colour distinction|Create a multi-page visual system|Direct a complex information design"),
  catalogue("art", "photography", 1, 6,
    "Hold a camera steady at a slow shutter|Focus on a chosen subject|Expose for a bright subject|Freeze a moving subject|Use depth of field deliberately|Photograph a subject in window light|Balance foreground and background|Capture consistent images across a series|Light a portrait with one source|Plan a documentary photo sequence|Photograph a high-contrast scene reliably"),
  catalogue("art", "craft-making", 1, 6,
    "Measure and mark craft material|Cut a clean edge in sheet material|Fold material along a scored line|Create a reversible join|Apply an even surface finish|Build a stable three-dimensional form|Repeat a shape from a template|Repair a damaged handmade object|Combine rigid and flexible materials|Develop a prototype through three iterations|Produce a matched set of handmade objects"),
  catalogue("art", "video-motion", 2, 6,
    "Frame a continuous thirty-second shot|Record clear speech with ambient sound|Cut on an action|Match colour across two shots|Build a title sequence|Create a smooth animated transition|Synchronise sound to visible action|Edit a three-minute narrative|Plan coverage for a short scene|Develop motion rules for a visual system"),
  catalogue("art", "performance", 1, 6,
    "Project the voice across a small room|Memorise a one-minute performance text|Hold a character objective through a scene|Respond to a scene partner in the moment|Use pauses to shape a performance|Adapt blocking to a changed space|Sustain a thirty-minute live performance"),

  catalogue("eng", "programming-fundamentals", 1, 6,
    "Assign and update a variable|Use a conditional to select behaviour|Repeat an operation with a loop|Define a function with two parameters|Transform a list of values|Handle a missing input explicitly|Read data from a text file|Write structured data to a file|Compose small functions into a workflow|Model a domain value with a type|Handle asynchronous completion|Design a small module boundary|Refactor duplicated logic|Implement validation at an input boundary|Write deterministic unit tests|Build a command-line program|Design a reusable application library|Implement a state machine|Structure a medium-sized codebase|Evolve an interface without breaking callers|Design a programming abstraction"),
  catalogue("eng", "data-structures-algorithms", 2, 6,
    "Use a map for keyed lookup|Traverse a tree iteratively|Implement a queue with bounded memory|Sort records by multiple keys|Search a sorted collection efficiently|Detect repeated values in linear time|Represent a graph with adjacency lists|Find a shortest unweighted path|Analyse time complexity of nested loops|Choose an algorithm under memory limits|Optimise a slow collection operation|Design an algorithm from invariants|Prove termination for an iterative algorithm"),
  catalogue("eng", "data-handling", 2, 6,
    "Validate fields in an input record|Normalise inconsistent text values|Join records using a stable key|Aggregate records by category|Detect missing values in a dataset|Convert data between structured formats|Stream records larger than memory|Preserve provenance through a transformation|Design an idempotent data import|Reconcile conflicting records|Build a repeatable data pipeline|Profile and optimise a data transformation|Design a versioned data contract"),
  catalogue("eng", "web-frontend", 2, 6,
    "Build a semantic page structure|Style a responsive content column|Create an accessible navigation menu|Validate a form before submission|Manage focus after an interface change|Render a list from structured data|Handle loading and error states|Persist interface state locally|Test keyboard interaction|Optimise images for responsive delivery|Build a reusable component system|Diagnose a layout across viewport sizes|Implement an offline interface fallback"),
  catalogue("eng", "debugging", 2, 6,
    "Reproduce a reported software defect|Reduce a failure to a minimal case|Inspect state at a breakpoint|Trace data through three functions|Separate symptoms from root cause|Bisect a behavioural regression|Diagnose a timing-dependent failure|Analyse a memory-growth problem|Debug a failure across service boundaries|Design instrumentation for an intermittent fault|Lead a structured incident investigation"),
  catalogue("eng", "systems-networking", 2, 7,
    "Inspect a process listening on a port|Trace name resolution for a host|Test connectivity across one network hop|Interpret an application protocol exchange|Configure a service health check|Diagnose resource exhaustion|Automate a repeatable service deployment|Design graceful shutdown behaviour|Trace latency across service boundaries|Engineer a resilient distributed platform|Plan capacity for variable load|Test recovery from a node failure"),
  catalogue("eng", "security", 2, 7,
    "Apply least privilege to a service account|Validate untrusted input at a boundary|Store credentials outside source code|Rotate a compromised secret|Review an access-control rule set|Model threats for a small service|Verify audit logs capture critical events|Harden a service against common misuse|Test an owned service for injection defensively|Lead defensive security architecture review|Design separation of security duties|Investigate a suspected service compromise"),
  catalogue("eng", "version-control", 1, 6,
    "Compare two code revisions|Restore one file from an earlier revision|Create a branch for isolated work|Combine non-conflicting branches|Resolve a textual merge conflict|Rewrite a local change into clear commits|Locate the revision that introduced a defect|Review a proposed change systematically|Coordinate parallel changes across contributors"),
];
